import React from 'react';
import FAQ from 'react-faq-component';
import '../LoginComponents/CSSFolder/Div5.css';

const data = {
  rows: [
    {
      title: 'How Does Tustify work?',
      content: `Tustify uses artificial intelligence to assist you in quickly generating content. Simply input your data, and you'll receive the finished result without any hassle.`,
    },
    {
      title: 'Is Tustify safe to use?',
      content: 'Absolutely, Tustify is completely safe to use. We prioritize your security and privacy, ensuring that all our features are created with your safety in mind.',
    },
    {
      title: 'I am not a professional writer. Will Tustify still be helpful?',
      content: `Certainly, Tustify can assist you in getting better at writing, no matter your skill level.`,
    },
    {
      title: 'Which kind of content can I create with Tustify?',
      content: 'You can use Tustify to make all kinds of content like blog posts, social media updates, promotions, articles, emails, and website content.',
    },
    {
      title: 'Who can use Tustify?',
      content: 'Tustify is a content creation tool for everyone, regardless of profession or writing expertise. Professional writers also benefit from its AI-powered, SEO-optimized content, saving time and providing valuable insights for audience engagement.',
    },
    {
      title: 'How can I control the tone and style of the content generated by Tustify?',
      content: 'Users can select the desired tone and style from a dropdown menu with various options. The content generated by the API will then align with the chosen tone and style specified in the selection.',
    },
  ],
};

const styles = {
  bgColor: 'white',
  rowTitleColor: 'black',
  rowContentColor: '#545353',
  arrowColor: 'black',
};

const config = {
  animate: true,
  arrowIcon: 'V',
  tabFocus: true,
};

export default function Div5() {
  return (
    <div id='FAQ1'>
      <h2 id='FAQ'>Frequently Asked Questions</h2>
      <FAQ data={data} styles={styles} config={config} />
    </div>
  );
}
